/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"


@protocol AmityService <NSObject>
- (NSString *) echo: (NSString *) request;  // throws TException
@end

@interface AmityServiceClient : NSObject <AmityService> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface AmityServiceProcessor : NSObject <TProcessor> {
  id <AmityService> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithAmityService: (id <AmityService>) service;
- (id<AmityService>) service;
@end

@interface amityConstants : NSObject {
}
@end
