/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"


#import "authentication.h"

@implementation AmityToken

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithValue: (NSString *) value
{
  self = [super init];
  __value = [value retain_stub];
  __value_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"value"])
  {
    __value = [[decoder decodeObjectForKey: @"value"] retain_stub];
    __value_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__value_isset)
  {
    [encoder encodeObject: __value forKey: @"value"];
  }
}

- (void) dealloc
{
  [__value release_stub];
  [super dealloc_stub];
}

- (NSString *) value {
  return [[__value retain_stub] autorelease_stub];
}

- (void) setValue: (NSString *) value {
  [value retain_stub];
  [__value release_stub];
  __value = value;
  __value_isset = YES;
}

- (BOOL) valueIsSet {
  return __value_isset;
}

- (void) unsetValue {
  [__value release_stub];
  __value = nil;
  __value_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setValue: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"AmityToken"];
  if (__value_isset) {
    if (__value != nil) {
      [outProtocol writeFieldBeginWithName: @"value" type: TType_STRING fieldID: 1];
      [outProtocol writeString: __value];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
  if (!__value_isset) {
    @throw [TProtocolException exceptionWithName: @"TProtocolException"
                               reason: @"Required field 'value' is not set."];
  }
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"AmityToken("];
  [ms appendString: @"value:"];
  [ms appendFormat: @"\"%@\"", __value];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@implementation LoginFacebookAccountRequest

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithFacebookId: (int64_t) facebookId emailAddress: (NSString *) emailAddress facebookToken: (NSString *) facebookToken
{
  self = [super init];
  __facebookId = facebookId;
  __facebookId_isset = YES;
  __emailAddress = [emailAddress retain_stub];
  __emailAddress_isset = YES;
  __facebookToken = [facebookToken retain_stub];
  __facebookToken_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"facebookId"])
  {
    __facebookId = [decoder decodeInt64ForKey: @"facebookId"];
    __facebookId_isset = YES;
  }
  if ([decoder containsValueForKey: @"emailAddress"])
  {
    __emailAddress = [[decoder decodeObjectForKey: @"emailAddress"] retain_stub];
    __emailAddress_isset = YES;
  }
  if ([decoder containsValueForKey: @"facebookToken"])
  {
    __facebookToken = [[decoder decodeObjectForKey: @"facebookToken"] retain_stub];
    __facebookToken_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__facebookId_isset)
  {
    [encoder encodeInt64: __facebookId forKey: @"facebookId"];
  }
  if (__emailAddress_isset)
  {
    [encoder encodeObject: __emailAddress forKey: @"emailAddress"];
  }
  if (__facebookToken_isset)
  {
    [encoder encodeObject: __facebookToken forKey: @"facebookToken"];
  }
}

- (void) dealloc
{
  [__emailAddress release_stub];
  [__facebookToken release_stub];
  [super dealloc_stub];
}

- (int64_t) facebookId {
  return __facebookId;
}

- (void) setFacebookId: (int64_t) facebookId {
  __facebookId = facebookId;
  __facebookId_isset = YES;
}

- (BOOL) facebookIdIsSet {
  return __facebookId_isset;
}

- (void) unsetFacebookId {
  __facebookId_isset = NO;
}

- (NSString *) emailAddress {
  return [[__emailAddress retain_stub] autorelease_stub];
}

- (void) setEmailAddress: (NSString *) emailAddress {
  [emailAddress retain_stub];
  [__emailAddress release_stub];
  __emailAddress = emailAddress;
  __emailAddress_isset = YES;
}

- (BOOL) emailAddressIsSet {
  return __emailAddress_isset;
}

- (void) unsetEmailAddress {
  [__emailAddress release_stub];
  __emailAddress = nil;
  __emailAddress_isset = NO;
}

- (NSString *) facebookToken {
  return [[__facebookToken retain_stub] autorelease_stub];
}

- (void) setFacebookToken: (NSString *) facebookToken {
  [facebookToken retain_stub];
  [__facebookToken release_stub];
  __facebookToken = facebookToken;
  __facebookToken_isset = YES;
}

- (BOOL) facebookTokenIsSet {
  return __facebookToken_isset;
}

- (void) unsetFacebookToken {
  [__facebookToken release_stub];
  __facebookToken = nil;
  __facebookToken_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setFacebookId: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setEmailAddress: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 3:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setFacebookToken: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"LoginFacebookAccountRequest"];
  if (__facebookId_isset) {
    [outProtocol writeFieldBeginWithName: @"facebookId" type: TType_I64 fieldID: 1];
    [outProtocol writeI64: __facebookId];
    [outProtocol writeFieldEnd];
  }
  if (__emailAddress_isset) {
    if (__emailAddress != nil) {
      [outProtocol writeFieldBeginWithName: @"emailAddress" type: TType_STRING fieldID: 2];
      [outProtocol writeString: __emailAddress];
      [outProtocol writeFieldEnd];
    }
  }
  if (__facebookToken_isset) {
    if (__facebookToken != nil) {
      [outProtocol writeFieldBeginWithName: @"facebookToken" type: TType_STRING fieldID: 3];
      [outProtocol writeString: __facebookToken];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
  if (!__facebookId_isset) {
    @throw [TProtocolException exceptionWithName: @"TProtocolException"
                               reason: @"Required field 'facebookId' is not set."];
  }
  if (!__emailAddress_isset) {
    @throw [TProtocolException exceptionWithName: @"TProtocolException"
                               reason: @"Required field 'emailAddress' is not set."];
  }
  if (!__facebookToken_isset) {
    @throw [TProtocolException exceptionWithName: @"TProtocolException"
                               reason: @"Required field 'facebookToken' is not set."];
  }
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"LoginFacebookAccountRequest("];
  [ms appendString: @"facebookId:"];
  [ms appendFormat: @"%qi", __facebookId];
  [ms appendString: @",emailAddress:"];
  [ms appendFormat: @"\"%@\"", __emailAddress];
  [ms appendString: @",facebookToken:"];
  [ms appendFormat: @"\"%@\"", __facebookToken];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@implementation LoginFacebookAccountResponse

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithFacebookId: (int64_t) facebookId authToken: (AmityToken *) authToken sessionToken: (AmityToken *) sessionToken
{
  self = [super init];
  __facebookId = facebookId;
  __facebookId_isset = YES;
  __authToken = [authToken retain_stub];
  __authToken_isset = YES;
  __sessionToken = [sessionToken retain_stub];
  __sessionToken_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"facebookId"])
  {
    __facebookId = [decoder decodeInt64ForKey: @"facebookId"];
    __facebookId_isset = YES;
  }
  if ([decoder containsValueForKey: @"authToken"])
  {
    __authToken = [[decoder decodeObjectForKey: @"authToken"] retain_stub];
    __authToken_isset = YES;
  }
  if ([decoder containsValueForKey: @"sessionToken"])
  {
    __sessionToken = [[decoder decodeObjectForKey: @"sessionToken"] retain_stub];
    __sessionToken_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__facebookId_isset)
  {
    [encoder encodeInt64: __facebookId forKey: @"facebookId"];
  }
  if (__authToken_isset)
  {
    [encoder encodeObject: __authToken forKey: @"authToken"];
  }
  if (__sessionToken_isset)
  {
    [encoder encodeObject: __sessionToken forKey: @"sessionToken"];
  }
}

- (void) dealloc
{
  [__authToken release_stub];
  [__sessionToken release_stub];
  [super dealloc_stub];
}

- (int64_t) facebookId {
  return __facebookId;
}

- (void) setFacebookId: (int64_t) facebookId {
  __facebookId = facebookId;
  __facebookId_isset = YES;
}

- (BOOL) facebookIdIsSet {
  return __facebookId_isset;
}

- (void) unsetFacebookId {
  __facebookId_isset = NO;
}

- (AmityToken *) authToken {
  return [[__authToken retain_stub] autorelease_stub];
}

- (void) setAuthToken: (AmityToken *) authToken {
  [authToken retain_stub];
  [__authToken release_stub];
  __authToken = authToken;
  __authToken_isset = YES;
}

- (BOOL) authTokenIsSet {
  return __authToken_isset;
}

- (void) unsetAuthToken {
  [__authToken release_stub];
  __authToken = nil;
  __authToken_isset = NO;
}

- (AmityToken *) sessionToken {
  return [[__sessionToken retain_stub] autorelease_stub];
}

- (void) setSessionToken: (AmityToken *) sessionToken {
  [sessionToken retain_stub];
  [__sessionToken release_stub];
  __sessionToken = sessionToken;
  __sessionToken_isset = YES;
}

- (BOOL) sessionTokenIsSet {
  return __sessionToken_isset;
}

- (void) unsetSessionToken {
  [__sessionToken release_stub];
  __sessionToken = nil;
  __sessionToken_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setFacebookId: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_STRUCT) {
          AmityToken *fieldValue = [[AmityToken alloc] init];
          [fieldValue read: inProtocol];
          [self setAuthToken: fieldValue];
          [fieldValue release_stub];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 3:
        if (fieldType == TType_STRUCT) {
          AmityToken *fieldValue = [[AmityToken alloc] init];
          [fieldValue read: inProtocol];
          [self setSessionToken: fieldValue];
          [fieldValue release_stub];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"LoginFacebookAccountResponse"];
  if (__facebookId_isset) {
    [outProtocol writeFieldBeginWithName: @"facebookId" type: TType_I64 fieldID: 1];
    [outProtocol writeI64: __facebookId];
    [outProtocol writeFieldEnd];
  }
  if (__authToken_isset) {
    if (__authToken != nil) {
      [outProtocol writeFieldBeginWithName: @"authToken" type: TType_STRUCT fieldID: 2];
      [__authToken write: outProtocol];
      [outProtocol writeFieldEnd];
    }
  }
  if (__sessionToken_isset) {
    if (__sessionToken != nil) {
      [outProtocol writeFieldBeginWithName: @"sessionToken" type: TType_STRUCT fieldID: 3];
      [__sessionToken write: outProtocol];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
  if (!__facebookId_isset) {
    @throw [TProtocolException exceptionWithName: @"TProtocolException"
                               reason: @"Required field 'facebookId' is not set."];
  }
  if (!__authToken_isset) {
    @throw [TProtocolException exceptionWithName: @"TProtocolException"
                               reason: @"Required field 'authToken' is not set."];
  }
  if (!__sessionToken_isset) {
    @throw [TProtocolException exceptionWithName: @"TProtocolException"
                               reason: @"Required field 'sessionToken' is not set."];
  }
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"LoginFacebookAccountResponse("];
  [ms appendString: @"facebookId:"];
  [ms appendFormat: @"%qi", __facebookId];
  [ms appendString: @",authToken:"];
  [ms appendFormat: @"%@", __authToken];
  [ms appendString: @",sessionToken:"];
  [ms appendFormat: @"%@", __sessionToken];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end


@implementation authenticationConstants
+ (void) initialize {
}
@end

@interface loginFacebookAccount_args : NSObject <TBase, NSCoding> {
  LoginFacebookAccountRequest * __request;

  BOOL __request_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=request, setter=setRequest:) LoginFacebookAccountRequest * request;
#endif

- (id) init;
- (id) initWithRequest: (LoginFacebookAccountRequest *) request;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (LoginFacebookAccountRequest *) request;
- (void) setRequest: (LoginFacebookAccountRequest *) request;
#endif
- (BOOL) requestIsSet;

@end

@implementation loginFacebookAccount_args

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithRequest: (LoginFacebookAccountRequest *) request
{
  self = [super init];
  __request = [request retain_stub];
  __request_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"request"])
  {
    __request = [[decoder decodeObjectForKey: @"request"] retain_stub];
    __request_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__request_isset)
  {
    [encoder encodeObject: __request forKey: @"request"];
  }
}

- (void) dealloc
{
  [__request release_stub];
  [super dealloc_stub];
}

- (LoginFacebookAccountRequest *) request {
  return [[__request retain_stub] autorelease_stub];
}

- (void) setRequest: (LoginFacebookAccountRequest *) request {
  [request retain_stub];
  [__request release_stub];
  __request = request;
  __request_isset = YES;
}

- (BOOL) requestIsSet {
  return __request_isset;
}

- (void) unsetRequest {
  [__request release_stub];
  __request = nil;
  __request_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_STRUCT) {
          LoginFacebookAccountRequest *fieldValue = [[LoginFacebookAccountRequest alloc] init];
          [fieldValue read: inProtocol];
          [self setRequest: fieldValue];
          [fieldValue release_stub];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"loginFacebookAccount_args"];
  if (__request_isset) {
    if (__request != nil) {
      [outProtocol writeFieldBeginWithName: @"request" type: TType_STRUCT fieldID: 1];
      [__request write: outProtocol];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"loginFacebookAccount_args("];
  [ms appendString: @"request:"];
  [ms appendFormat: @"%@", __request];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@interface LoginFacebookAccount_result : NSObject <TBase, NSCoding> {
  LoginFacebookAccountResponse * __success;

  BOOL __success_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=success, setter=setSuccess:) LoginFacebookAccountResponse * success;
#endif

- (id) init;
- (id) initWithSuccess: (LoginFacebookAccountResponse *) success;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (LoginFacebookAccountResponse *) success;
- (void) setSuccess: (LoginFacebookAccountResponse *) success;
#endif
- (BOOL) successIsSet;

@end

@implementation LoginFacebookAccount_result

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithSuccess: (LoginFacebookAccountResponse *) success
{
  self = [super init];
  __success = [success retain_stub];
  __success_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"success"])
  {
    __success = [[decoder decodeObjectForKey: @"success"] retain_stub];
    __success_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__success_isset)
  {
    [encoder encodeObject: __success forKey: @"success"];
  }
}

- (void) dealloc
{
  [__success release_stub];
  [super dealloc_stub];
}

- (LoginFacebookAccountResponse *) success {
  return [[__success retain_stub] autorelease_stub];
}

- (void) setSuccess: (LoginFacebookAccountResponse *) success {
  [success retain_stub];
  [__success release_stub];
  __success = success;
  __success_isset = YES;
}

- (BOOL) successIsSet {
  return __success_isset;
}

- (void) unsetSuccess {
  [__success release_stub];
  __success = nil;
  __success_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 0:
        if (fieldType == TType_STRUCT) {
          LoginFacebookAccountResponse *fieldValue = [[LoginFacebookAccountResponse alloc] init];
          [fieldValue read: inProtocol];
          [self setSuccess: fieldValue];
          [fieldValue release_stub];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"LoginFacebookAccount_result"];

  if (__success_isset) {
    if (__success != nil) {
      [outProtocol writeFieldBeginWithName: @"success" type: TType_STRUCT fieldID: 0];
      [__success write: outProtocol];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"LoginFacebookAccount_result("];
  [ms appendString: @"success:"];
  [ms appendFormat: @"%@", __success];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@implementation AuthenticationThriftServiceClient
- (id) initWithProtocol: (id <TProtocol>) protocol
{
  return [self initWithInProtocol: protocol outProtocol: protocol];
}

- (id) initWithInProtocol: (id <TProtocol>) anInProtocol outProtocol: (id <TProtocol>) anOutProtocol
{
  self = [super init];
  inProtocol = [anInProtocol retain_stub];
  outProtocol = [anOutProtocol retain_stub];
  return self;
}

- (void) dealloc
{
  [inProtocol release_stub];
  [outProtocol release_stub];
  [super dealloc_stub];
}

- (void) send_loginFacebookAccount: (LoginFacebookAccountRequest *) request
{
  [outProtocol writeMessageBeginWithName: @"loginFacebookAccount" type: TMessageType_CALL sequenceID: 0];
  [outProtocol writeStructBeginWithName: @"loginFacebookAccount_args"];
  if (request != nil)  {
    [outProtocol writeFieldBeginWithName: @"request" type: TType_STRUCT fieldID: 1];
    [request write: outProtocol];
    [outProtocol writeFieldEnd];
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
  [outProtocol writeMessageEnd];
  [[outProtocol transport] flush];
}

- (LoginFacebookAccountResponse *) recv_loginFacebookAccount
{
  int msgType = 0;
  [inProtocol readMessageBeginReturningName: nil type: &msgType sequenceID: NULL];
  if (msgType == TMessageType_EXCEPTION) {
    TApplicationException * x = [TApplicationException read: inProtocol];
    [inProtocol readMessageEnd];
    @throw x;
  }
  LoginFacebookAccount_result * result = [[[LoginFacebookAccount_result alloc] init] autorelease_stub];
  [result read: inProtocol];
  [inProtocol readMessageEnd];
  if ([result successIsSet]) {
    return [result success];
  }
  @throw [TApplicationException exceptionWithType: TApplicationException_MISSING_RESULT
                                           reason: @"loginFacebookAccount failed: unknown result"];
}

- (LoginFacebookAccountResponse *) loginFacebookAccount: (LoginFacebookAccountRequest *) request
{
  [self send_loginFacebookAccount : request];
  return [self recv_loginFacebookAccount];
}

@end

@implementation AuthenticationThriftServiceProcessor

- (id) initWithAuthenticationThriftService: (id <AuthenticationThriftService>) service
{
  self = [super init];
  if (!self) {
    return nil;
  }
  mService = [service retain_stub];
  mMethodMap = [[NSMutableDictionary dictionary] retain_stub];
  {
    SEL s = @selector(process_loginFacebookAccount_withSequenceID:inProtocol:outProtocol:);
    NSMethodSignature * sig = [self methodSignatureForSelector: s];
    NSInvocation * invocation = [NSInvocation invocationWithMethodSignature: sig];
    [invocation setSelector: s];
    [invocation retainArguments];
    [mMethodMap setValue: invocation forKey: @"loginFacebookAccount"];
  }
  return self;
}

- (id<AuthenticationThriftService>) service
{
  return [[mService retain_stub] autorelease_stub];
}

- (BOOL) processOnInputProtocol: (id <TProtocol>) inProtocol
                 outputProtocol: (id <TProtocol>) outProtocol
{
  NSString * messageName;
  int messageType;
  int seqID;
  [inProtocol readMessageBeginReturningName: &messageName
                                       type: &messageType
                                 sequenceID: &seqID];
  NSInvocation * invocation = [mMethodMap valueForKey: messageName];
  if (invocation == nil) {
    [TProtocolUtil skipType: TType_STRUCT onProtocol: inProtocol];
    [inProtocol readMessageEnd];
    TApplicationException * x = [TApplicationException exceptionWithType: TApplicationException_UNKNOWN_METHOD reason: [NSString stringWithFormat: @"Invalid method name: '%@'", messageName]];
    [outProtocol writeMessageBeginWithName: messageName
                                      type: TMessageType_EXCEPTION
                                sequenceID: seqID];
    [x write: outProtocol];
    [outProtocol writeMessageEnd];
    [[outProtocol transport] flush];
    return YES;
  }
  // NSInvocation does not conform to NSCopying protocol
  NSInvocation * i = [NSInvocation invocationWithMethodSignature: [invocation methodSignature]];
  [i setSelector: [invocation selector]];
  [i setArgument: &seqID atIndex: 2];
  [i setArgument: &inProtocol atIndex: 3];
  [i setArgument: &outProtocol atIndex: 4];
  [i setTarget: self];
  [i invoke];
  return YES;
}

- (void) process_loginFacebookAccount_withSequenceID: (int32_t) seqID inProtocol: (id<TProtocol>) inProtocol outProtocol: (id<TProtocol>) outProtocol
{
  loginFacebookAccount_args * args = [[loginFacebookAccount_args alloc] init];
  [args read: inProtocol];
  [inProtocol readMessageEnd];
  LoginFacebookAccount_result * result = [[LoginFacebookAccount_result alloc] init];
  [result setSuccess: [mService loginFacebookAccount: [args request]]];
  [outProtocol writeMessageBeginWithName: @"loginFacebookAccount"
                                    type: TMessageType_REPLY
                              sequenceID: seqID];
  [result write: outProtocol];
  [outProtocol writeMessageEnd];
  [[outProtocol transport] flush];
  [result release_stub];
  [args release_stub];
}

- (void) dealloc
{
  [mService release_stub];
  [mMethodMap release_stub];
  [super dealloc_stub];
}

@end

