/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"

#import "Authentication.h"
#import "RefData.h"

@interface HelpRequestDto : NSObject <TBase, NSCoding> {
  int64_t __id;
  int64_t __userId;
  int32_t __fromCityId;
  NSString * __fromDate;
  int32_t __toCityId;
  NSString * __toDate;
  CityDto * __fromCity;
  CityDto * __toCity;

  BOOL __id_isset;
  BOOL __userId_isset;
  BOOL __fromCityId_isset;
  BOOL __fromDate_isset;
  BOOL __toCityId_isset;
  BOOL __toDate_isset;
  BOOL __fromCity_isset;
  BOOL __toCity_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=id, setter=setId:) int64_t id;
@property (nonatomic, getter=userId, setter=setUserId:) int64_t userId;
@property (nonatomic, getter=fromCityId, setter=setFromCityId:) int32_t fromCityId;
@property (nonatomic, retain, getter=fromDate, setter=setFromDate:) NSString * fromDate;
@property (nonatomic, getter=toCityId, setter=setToCityId:) int32_t toCityId;
@property (nonatomic, retain, getter=toDate, setter=setToDate:) NSString * toDate;
@property (nonatomic, retain, getter=fromCity, setter=setFromCity:) CityDto * fromCity;
@property (nonatomic, retain, getter=toCity, setter=setToCity:) CityDto * toCity;
#endif

- (id) init;
- (id) initWithId: (int64_t) id userId: (int64_t) userId fromCityId: (int32_t) fromCityId fromDate: (NSString *) fromDate toCityId: (int32_t) toCityId toDate: (NSString *) toDate fromCity: (CityDto *) fromCity toCity: (CityDto *) toCity;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int64_t) id;
- (void) setId: (int64_t) id;
#endif
- (BOOL) idIsSet;

#if !__has_feature(objc_arc)
- (int64_t) userId;
- (void) setUserId: (int64_t) userId;
#endif
- (BOOL) userIdIsSet;

#if !__has_feature(objc_arc)
- (int32_t) fromCityId;
- (void) setFromCityId: (int32_t) fromCityId;
#endif
- (BOOL) fromCityIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) fromDate;
- (void) setFromDate: (NSString *) fromDate;
#endif
- (BOOL) fromDateIsSet;

#if !__has_feature(objc_arc)
- (int32_t) toCityId;
- (void) setToCityId: (int32_t) toCityId;
#endif
- (BOOL) toCityIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) toDate;
- (void) setToDate: (NSString *) toDate;
#endif
- (BOOL) toDateIsSet;

#if !__has_feature(objc_arc)
- (CityDto *) fromCity;
- (void) setFromCity: (CityDto *) fromCity;
#endif
- (BOOL) fromCityIsSet;

#if !__has_feature(objc_arc)
- (CityDto *) toCity;
- (void) setToCity: (CityDto *) toCity;
#endif
- (BOOL) toCityIsSet;

@end

@interface GetHelpRequestRequest : NSObject <TBase, NSCoding> {
  int64_t __helpRequestId;

  BOOL __helpRequestId_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=helpRequestId, setter=setHelpRequestId:) int64_t helpRequestId;
#endif

- (id) init;
- (id) initWithHelpRequestId: (int64_t) helpRequestId;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int64_t) helpRequestId;
- (void) setHelpRequestId: (int64_t) helpRequestId;
#endif
- (BOOL) helpRequestIdIsSet;

@end

@interface GetHelpRequestResponse : NSObject <TBase, NSCoding> {
  int32_t __errorCode;
  HelpRequestDto * __helpRequest;

  BOOL __errorCode_isset;
  BOOL __helpRequest_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=errorCode, setter=setErrorCode:) int32_t errorCode;
@property (nonatomic, retain, getter=helpRequest, setter=setHelpRequest:) HelpRequestDto * helpRequest;
#endif

- (id) init;
- (id) initWithErrorCode: (int32_t) errorCode helpRequest: (HelpRequestDto *) helpRequest;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) errorCode;
- (void) setErrorCode: (int32_t) errorCode;
#endif
- (BOOL) errorCodeIsSet;

#if !__has_feature(objc_arc)
- (HelpRequestDto *) helpRequest;
- (void) setHelpRequest: (HelpRequestDto *) helpRequest;
#endif
- (BOOL) helpRequestIsSet;

@end

@interface ListHelpRequestRequest : NSObject <TBase, NSCoding> {
  int64_t __amityUserId;

  BOOL __amityUserId_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=amityUserId, setter=setAmityUserId:) int64_t amityUserId;
#endif

- (id) init;
- (id) initWithAmityUserId: (int64_t) amityUserId;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int64_t) amityUserId;
- (void) setAmityUserId: (int64_t) amityUserId;
#endif
- (BOOL) amityUserIdIsSet;

@end

@interface ListHelpRequestResponse : NSObject <TBase, NSCoding> {
  int32_t __errorCode;
  NSMutableArray * __helpRequests;

  BOOL __errorCode_isset;
  BOOL __helpRequests_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=errorCode, setter=setErrorCode:) int32_t errorCode;
@property (nonatomic, retain, getter=helpRequests, setter=setHelpRequests:) NSMutableArray * helpRequests;
#endif

- (id) init;
- (id) initWithErrorCode: (int32_t) errorCode helpRequests: (NSMutableArray *) helpRequests;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) errorCode;
- (void) setErrorCode: (int32_t) errorCode;
#endif
- (BOOL) errorCodeIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) helpRequests;
- (void) setHelpRequests: (NSMutableArray *) helpRequests;
#endif
- (BOOL) helpRequestsIsSet;

@end

@interface CreateHelpRequestRequest : NSObject <TBase, NSCoding> {
  HelpRequestDto * __helpRequest;

  BOOL __helpRequest_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=helpRequest, setter=setHelpRequest:) HelpRequestDto * helpRequest;
#endif

- (id) init;
- (id) initWithHelpRequest: (HelpRequestDto *) helpRequest;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (HelpRequestDto *) helpRequest;
- (void) setHelpRequest: (HelpRequestDto *) helpRequest;
#endif
- (BOOL) helpRequestIsSet;

@end

@interface CreateHelpRequestResponse : NSObject <TBase, NSCoding> {
  int32_t __errorCode;
  int64_t __helpRequestId;

  BOOL __errorCode_isset;
  BOOL __helpRequestId_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=errorCode, setter=setErrorCode:) int32_t errorCode;
@property (nonatomic, getter=helpRequestId, setter=setHelpRequestId:) int64_t helpRequestId;
#endif

- (id) init;
- (id) initWithErrorCode: (int32_t) errorCode helpRequestId: (int64_t) helpRequestId;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) errorCode;
- (void) setErrorCode: (int32_t) errorCode;
#endif
- (BOOL) errorCodeIsSet;

#if !__has_feature(objc_arc)
- (int64_t) helpRequestId;
- (void) setHelpRequestId: (int64_t) helpRequestId;
#endif
- (BOOL) helpRequestIdIsSet;

@end

@interface UpdateHelpRequestRequest : NSObject <TBase, NSCoding> {
  HelpRequestDto * __helpRequest;

  BOOL __helpRequest_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=helpRequest, setter=setHelpRequest:) HelpRequestDto * helpRequest;
#endif

- (id) init;
- (id) initWithHelpRequest: (HelpRequestDto *) helpRequest;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (HelpRequestDto *) helpRequest;
- (void) setHelpRequest: (HelpRequestDto *) helpRequest;
#endif
- (BOOL) helpRequestIsSet;

@end

@interface UpdateHelpRequestResponse : NSObject <TBase, NSCoding> {
  int32_t __errorCode;

  BOOL __errorCode_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=errorCode, setter=setErrorCode:) int32_t errorCode;
#endif

- (id) init;
- (id) initWithErrorCode: (int32_t) errorCode;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) errorCode;
- (void) setErrorCode: (int32_t) errorCode;
#endif
- (BOOL) errorCodeIsSet;

@end

@interface DeleteHelpRequestRequest : NSObject <TBase, NSCoding> {
  int64_t __helpRequestId;

  BOOL __helpRequestId_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=helpRequestId, setter=setHelpRequestId:) int64_t helpRequestId;
#endif

- (id) init;
- (id) initWithHelpRequestId: (int64_t) helpRequestId;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int64_t) helpRequestId;
- (void) setHelpRequestId: (int64_t) helpRequestId;
#endif
- (BOOL) helpRequestIdIsSet;

@end

@interface DeleteHelpRequestResponse : NSObject <TBase, NSCoding> {
  int32_t __errorCode;

  BOOL __errorCode_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=errorCode, setter=setErrorCode:) int32_t errorCode;
#endif

- (id) init;
- (id) initWithErrorCode: (int32_t) errorCode;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) errorCode;
- (void) setErrorCode: (int32_t) errorCode;
#endif
- (BOOL) errorCodeIsSet;

@end

@protocol HelpRequestThriftService <NSObject>
- (GetHelpRequestResponse *) getHelpRequest: (GetHelpRequestRequest *) request credentials: (SessionCredentials *) credentials;  // throws TException
- (ListHelpRequestResponse *) listHelpRequests: (ListHelpRequestRequest *) request credentials: (SessionCredentials *) credentials;  // throws TException
- (CreateHelpRequestResponse *) createHelpRequest: (CreateHelpRequestRequest *) request credentials: (SessionCredentials *) credentials;  // throws TException
- (UpdateHelpRequestResponse *) updateHelpRequest: (UpdateHelpRequestRequest *) request credentials: (SessionCredentials *) credentials;  // throws TException
- (DeleteHelpRequestResponse *) deleteHelpRequest: (DeleteHelpRequestRequest *) request credentials: (SessionCredentials *) credentials;  // throws TException
@end

@interface HelpRequestThriftServiceClient : NSObject <HelpRequestThriftService> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface HelpRequestThriftServiceProcessor : NSObject <TProcessor> {
  id <HelpRequestThriftService> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithHelpRequestThriftService: (id <HelpRequestThriftService>) service;
- (id<HelpRequestThriftService>) service;
@end

@interface HelpRequestConstants : NSObject {
}
@end
