/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"

#import "authentication.h"

@interface HelperItineraryDto : NSObject <TBase, NSCoding> {
  int64_t __id;
  int64_t __userId;
  int32_t __departureCityId;
  NSString * __departureDate;
  int32_t __arrivalCityId;
  NSString * __arrivalDate;

  BOOL __id_isset;
  BOOL __userId_isset;
  BOOL __departureCityId_isset;
  BOOL __departureDate_isset;
  BOOL __arrivalCityId_isset;
  BOOL __arrivalDate_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=id, setter=setId:) int64_t id;
@property (nonatomic, getter=userId, setter=setUserId:) int64_t userId;
@property (nonatomic, getter=departureCityId, setter=setDepartureCityId:) int32_t departureCityId;
@property (nonatomic, retain, getter=departureDate, setter=setDepartureDate:) NSString * departureDate;
@property (nonatomic, getter=arrivalCityId, setter=setArrivalCityId:) int32_t arrivalCityId;
@property (nonatomic, retain, getter=arrivalDate, setter=setArrivalDate:) NSString * arrivalDate;
#endif

- (id) init;
- (id) initWithId: (int64_t) id userId: (int64_t) userId departureCityId: (int32_t) departureCityId departureDate: (NSString *) departureDate arrivalCityId: (int32_t) arrivalCityId arrivalDate: (NSString *) arrivalDate;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int64_t) id;
- (void) setId: (int64_t) id;
#endif
- (BOOL) idIsSet;

#if !__has_feature(objc_arc)
- (int64_t) userId;
- (void) setUserId: (int64_t) userId;
#endif
- (BOOL) userIdIsSet;

#if !__has_feature(objc_arc)
- (int32_t) departureCityId;
- (void) setDepartureCityId: (int32_t) departureCityId;
#endif
- (BOOL) departureCityIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) departureDate;
- (void) setDepartureDate: (NSString *) departureDate;
#endif
- (BOOL) departureDateIsSet;

#if !__has_feature(objc_arc)
- (int32_t) arrivalCityId;
- (void) setArrivalCityId: (int32_t) arrivalCityId;
#endif
- (BOOL) arrivalCityIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) arrivalDate;
- (void) setArrivalDate: (NSString *) arrivalDate;
#endif
- (BOOL) arrivalDateIsSet;

@end

@interface CreateHelperItineraryRequest : NSObject <TBase, NSCoding> {
  HelperItineraryDto * __itinerary;

  BOOL __itinerary_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=itinerary, setter=setItinerary:) HelperItineraryDto * itinerary;
#endif

- (id) init;
- (id) initWithItinerary: (HelperItineraryDto *) itinerary;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (HelperItineraryDto *) itinerary;
- (void) setItinerary: (HelperItineraryDto *) itinerary;
#endif
- (BOOL) itineraryIsSet;

@end

@interface CreateHelperItineraryResponse : NSObject <TBase, NSCoding> {
  int32_t __errorCode;
  int64_t __itineraryId;

  BOOL __errorCode_isset;
  BOOL __itineraryId_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=errorCode, setter=setErrorCode:) int32_t errorCode;
@property (nonatomic, getter=itineraryId, setter=setItineraryId:) int64_t itineraryId;
#endif

- (id) init;
- (id) initWithErrorCode: (int32_t) errorCode itineraryId: (int64_t) itineraryId;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) errorCode;
- (void) setErrorCode: (int32_t) errorCode;
#endif
- (BOOL) errorCodeIsSet;

#if !__has_feature(objc_arc)
- (int64_t) itineraryId;
- (void) setItineraryId: (int64_t) itineraryId;
#endif
- (BOOL) itineraryIdIsSet;

@end

@protocol ItineraryThriftService <NSObject>
- (CreateHelperItineraryResponse *) createItinerary: (CreateHelperItineraryRequest *) request credentials: (SessionCredentials *) credentials;  // throws TException
@end

@interface ItineraryThriftServiceClient : NSObject <ItineraryThriftService> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface ItineraryThriftServiceProcessor : NSObject <TProcessor> {
  id <ItineraryThriftService> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithItineraryThriftService: (id <ItineraryThriftService>) service;
- (id<ItineraryThriftService>) service;
@end

@interface itineraryConstants : NSObject {
}
@end
