/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"


#import "itinerary.h"

@implementation HelperItineraryDto

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithId: (int64_t) id userId: (int64_t) userId fromLocationid: (int32_t) fromLocationid latestPickupDate: (NSString *) latestPickupDate toLocationId: (int32_t) toLocationId latestDeliveryDate: (NSString *) latestDeliveryDate
{
  self = [super init];
  __id = id;
  __id_isset = YES;
  __userId = userId;
  __userId_isset = YES;
  __fromLocationid = fromLocationid;
  __fromLocationid_isset = YES;
  __latestPickupDate = [latestPickupDate retain_stub];
  __latestPickupDate_isset = YES;
  __toLocationId = toLocationId;
  __toLocationId_isset = YES;
  __latestDeliveryDate = [latestDeliveryDate retain_stub];
  __latestDeliveryDate_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"id"])
  {
    __id = [decoder decodeInt64ForKey: @"id"];
    __id_isset = YES;
  }
  if ([decoder containsValueForKey: @"userId"])
  {
    __userId = [decoder decodeInt64ForKey: @"userId"];
    __userId_isset = YES;
  }
  if ([decoder containsValueForKey: @"fromLocationid"])
  {
    __fromLocationid = [decoder decodeInt32ForKey: @"fromLocationid"];
    __fromLocationid_isset = YES;
  }
  if ([decoder containsValueForKey: @"latestPickupDate"])
  {
    __latestPickupDate = [[decoder decodeObjectForKey: @"latestPickupDate"] retain_stub];
    __latestPickupDate_isset = YES;
  }
  if ([decoder containsValueForKey: @"toLocationId"])
  {
    __toLocationId = [decoder decodeInt32ForKey: @"toLocationId"];
    __toLocationId_isset = YES;
  }
  if ([decoder containsValueForKey: @"latestDeliveryDate"])
  {
    __latestDeliveryDate = [[decoder decodeObjectForKey: @"latestDeliveryDate"] retain_stub];
    __latestDeliveryDate_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__id_isset)
  {
    [encoder encodeInt64: __id forKey: @"id"];
  }
  if (__userId_isset)
  {
    [encoder encodeInt64: __userId forKey: @"userId"];
  }
  if (__fromLocationid_isset)
  {
    [encoder encodeInt32: __fromLocationid forKey: @"fromLocationid"];
  }
  if (__latestPickupDate_isset)
  {
    [encoder encodeObject: __latestPickupDate forKey: @"latestPickupDate"];
  }
  if (__toLocationId_isset)
  {
    [encoder encodeInt32: __toLocationId forKey: @"toLocationId"];
  }
  if (__latestDeliveryDate_isset)
  {
    [encoder encodeObject: __latestDeliveryDate forKey: @"latestDeliveryDate"];
  }
}

- (void) dealloc
{
  [__latestPickupDate release_stub];
  [__latestDeliveryDate release_stub];
  [super dealloc_stub];
}

- (int64_t) id {
  return __id;
}

- (void) setId: (int64_t) id {
  __id = id;
  __id_isset = YES;
}

- (BOOL) idIsSet {
  return __id_isset;
}

- (void) unsetId {
  __id_isset = NO;
}

- (int64_t) userId {
  return __userId;
}

- (void) setUserId: (int64_t) userId {
  __userId = userId;
  __userId_isset = YES;
}

- (BOOL) userIdIsSet {
  return __userId_isset;
}

- (void) unsetUserId {
  __userId_isset = NO;
}

- (int32_t) fromLocationid {
  return __fromLocationid;
}

- (void) setFromLocationid: (int32_t) fromLocationid {
  __fromLocationid = fromLocationid;
  __fromLocationid_isset = YES;
}

- (BOOL) fromLocationidIsSet {
  return __fromLocationid_isset;
}

- (void) unsetFromLocationid {
  __fromLocationid_isset = NO;
}

- (NSString *) latestPickupDate {
  return [[__latestPickupDate retain_stub] autorelease_stub];
}

- (void) setLatestPickupDate: (NSString *) latestPickupDate {
  [latestPickupDate retain_stub];
  [__latestPickupDate release_stub];
  __latestPickupDate = latestPickupDate;
  __latestPickupDate_isset = YES;
}

- (BOOL) latestPickupDateIsSet {
  return __latestPickupDate_isset;
}

- (void) unsetLatestPickupDate {
  [__latestPickupDate release_stub];
  __latestPickupDate = nil;
  __latestPickupDate_isset = NO;
}

- (int32_t) toLocationId {
  return __toLocationId;
}

- (void) setToLocationId: (int32_t) toLocationId {
  __toLocationId = toLocationId;
  __toLocationId_isset = YES;
}

- (BOOL) toLocationIdIsSet {
  return __toLocationId_isset;
}

- (void) unsetToLocationId {
  __toLocationId_isset = NO;
}

- (NSString *) latestDeliveryDate {
  return [[__latestDeliveryDate retain_stub] autorelease_stub];
}

- (void) setLatestDeliveryDate: (NSString *) latestDeliveryDate {
  [latestDeliveryDate retain_stub];
  [__latestDeliveryDate release_stub];
  __latestDeliveryDate = latestDeliveryDate;
  __latestDeliveryDate_isset = YES;
}

- (BOOL) latestDeliveryDateIsSet {
  return __latestDeliveryDate_isset;
}

- (void) unsetLatestDeliveryDate {
  [__latestDeliveryDate release_stub];
  __latestDeliveryDate = nil;
  __latestDeliveryDate_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setId: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 2:
        if (fieldType == TType_I64) {
          int64_t fieldValue = [inProtocol readI64];
          [self setUserId: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 3:
        if (fieldType == TType_I32) {
          int32_t fieldValue = [inProtocol readI32];
          [self setFromLocationid: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 4:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setLatestPickupDate: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 5:
        if (fieldType == TType_I32) {
          int32_t fieldValue = [inProtocol readI32];
          [self setToLocationId: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      case 6:
        if (fieldType == TType_STRING) {
          NSString * fieldValue = [inProtocol readString];
          [self setLatestDeliveryDate: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"HelperItineraryDto"];
  if (__id_isset) {
    [outProtocol writeFieldBeginWithName: @"id" type: TType_I64 fieldID: 1];
    [outProtocol writeI64: __id];
    [outProtocol writeFieldEnd];
  }
  if (__userId_isset) {
    [outProtocol writeFieldBeginWithName: @"userId" type: TType_I64 fieldID: 2];
    [outProtocol writeI64: __userId];
    [outProtocol writeFieldEnd];
  }
  if (__fromLocationid_isset) {
    [outProtocol writeFieldBeginWithName: @"fromLocationid" type: TType_I32 fieldID: 3];
    [outProtocol writeI32: __fromLocationid];
    [outProtocol writeFieldEnd];
  }
  if (__latestPickupDate_isset) {
    if (__latestPickupDate != nil) {
      [outProtocol writeFieldBeginWithName: @"latestPickupDate" type: TType_STRING fieldID: 4];
      [outProtocol writeString: __latestPickupDate];
      [outProtocol writeFieldEnd];
    }
  }
  if (__toLocationId_isset) {
    [outProtocol writeFieldBeginWithName: @"toLocationId" type: TType_I32 fieldID: 5];
    [outProtocol writeI32: __toLocationId];
    [outProtocol writeFieldEnd];
  }
  if (__latestDeliveryDate_isset) {
    if (__latestDeliveryDate != nil) {
      [outProtocol writeFieldBeginWithName: @"latestDeliveryDate" type: TType_STRING fieldID: 6];
      [outProtocol writeString: __latestDeliveryDate];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
  if (!__userId_isset) {
    @throw [TProtocolException exceptionWithName: @"TProtocolException"
                               reason: @"Required field 'userId' is not set."];
  }
  if (!__fromLocationid_isset) {
    @throw [TProtocolException exceptionWithName: @"TProtocolException"
                               reason: @"Required field 'fromLocationid' is not set."];
  }
  if (!__latestPickupDate_isset) {
    @throw [TProtocolException exceptionWithName: @"TProtocolException"
                               reason: @"Required field 'latestPickupDate' is not set."];
  }
  if (!__toLocationId_isset) {
    @throw [TProtocolException exceptionWithName: @"TProtocolException"
                               reason: @"Required field 'toLocationId' is not set."];
  }
  if (!__latestDeliveryDate_isset) {
    @throw [TProtocolException exceptionWithName: @"TProtocolException"
                               reason: @"Required field 'latestDeliveryDate' is not set."];
  }
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"HelperItineraryDto("];
  [ms appendString: @"id:"];
  [ms appendFormat: @"%qi", __id];
  [ms appendString: @",userId:"];
  [ms appendFormat: @"%qi", __userId];
  [ms appendString: @",fromLocationid:"];
  [ms appendFormat: @"%i", __fromLocationid];
  [ms appendString: @",latestPickupDate:"];
  [ms appendFormat: @"\"%@\"", __latestPickupDate];
  [ms appendString: @",toLocationId:"];
  [ms appendFormat: @"%i", __toLocationId];
  [ms appendString: @",latestDeliveryDate:"];
  [ms appendFormat: @"\"%@\"", __latestDeliveryDate];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@implementation CreateHelperItineraryRequest

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithItinerary: (HelperItineraryDto *) itinerary
{
  self = [super init];
  __itinerary = [itinerary retain_stub];
  __itinerary_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"itinerary"])
  {
    __itinerary = [[decoder decodeObjectForKey: @"itinerary"] retain_stub];
    __itinerary_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__itinerary_isset)
  {
    [encoder encodeObject: __itinerary forKey: @"itinerary"];
  }
}

- (void) dealloc
{
  [__itinerary release_stub];
  [super dealloc_stub];
}

- (HelperItineraryDto *) itinerary {
  return [[__itinerary retain_stub] autorelease_stub];
}

- (void) setItinerary: (HelperItineraryDto *) itinerary {
  [itinerary retain_stub];
  [__itinerary release_stub];
  __itinerary = itinerary;
  __itinerary_isset = YES;
}

- (BOOL) itineraryIsSet {
  return __itinerary_isset;
}

- (void) unsetItinerary {
  [__itinerary release_stub];
  __itinerary = nil;
  __itinerary_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_STRUCT) {
          HelperItineraryDto *fieldValue = [[HelperItineraryDto alloc] init];
          [fieldValue read: inProtocol];
          [self setItinerary: fieldValue];
          [fieldValue release_stub];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"CreateHelperItineraryRequest"];
  if (__itinerary_isset) {
    if (__itinerary != nil) {
      [outProtocol writeFieldBeginWithName: @"itinerary" type: TType_STRUCT fieldID: 1];
      [__itinerary write: outProtocol];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"CreateHelperItineraryRequest("];
  [ms appendString: @"itinerary:"];
  [ms appendFormat: @"%@", __itinerary];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@implementation CreateHelperItineraryResponse

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithItineraryId: (int32_t) itineraryId
{
  self = [super init];
  __itineraryId = itineraryId;
  __itineraryId_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"itineraryId"])
  {
    __itineraryId = [decoder decodeInt32ForKey: @"itineraryId"];
    __itineraryId_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__itineraryId_isset)
  {
    [encoder encodeInt32: __itineraryId forKey: @"itineraryId"];
  }
}

- (void) dealloc
{
  [super dealloc_stub];
}

- (int32_t) itineraryId {
  return __itineraryId;
}

- (void) setItineraryId: (int32_t) itineraryId {
  __itineraryId = itineraryId;
  __itineraryId_isset = YES;
}

- (BOOL) itineraryIdIsSet {
  return __itineraryId_isset;
}

- (void) unsetItineraryId {
  __itineraryId_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_I32) {
          int32_t fieldValue = [inProtocol readI32];
          [self setItineraryId: fieldValue];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"CreateHelperItineraryResponse"];
  if (__itineraryId_isset) {
    [outProtocol writeFieldBeginWithName: @"itineraryId" type: TType_I32 fieldID: 1];
    [outProtocol writeI32: __itineraryId];
    [outProtocol writeFieldEnd];
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"CreateHelperItineraryResponse("];
  [ms appendString: @"itineraryId:"];
  [ms appendFormat: @"%i", __itineraryId];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end


@implementation itineraryConstants
+ (void) initialize {
}
@end

@interface createItinerary_args : NSObject <TBase, NSCoding> {
  CreateHelperItineraryRequest * __request;

  BOOL __request_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=request, setter=setRequest:) CreateHelperItineraryRequest * request;
#endif

- (id) init;
- (id) initWithRequest: (CreateHelperItineraryRequest *) request;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (CreateHelperItineraryRequest *) request;
- (void) setRequest: (CreateHelperItineraryRequest *) request;
#endif
- (BOOL) requestIsSet;

@end

@implementation createItinerary_args

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithRequest: (CreateHelperItineraryRequest *) request
{
  self = [super init];
  __request = [request retain_stub];
  __request_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"request"])
  {
    __request = [[decoder decodeObjectForKey: @"request"] retain_stub];
    __request_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__request_isset)
  {
    [encoder encodeObject: __request forKey: @"request"];
  }
}

- (void) dealloc
{
  [__request release_stub];
  [super dealloc_stub];
}

- (CreateHelperItineraryRequest *) request {
  return [[__request retain_stub] autorelease_stub];
}

- (void) setRequest: (CreateHelperItineraryRequest *) request {
  [request retain_stub];
  [__request release_stub];
  __request = request;
  __request_isset = YES;
}

- (BOOL) requestIsSet {
  return __request_isset;
}

- (void) unsetRequest {
  [__request release_stub];
  __request = nil;
  __request_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 1:
        if (fieldType == TType_STRUCT) {
          CreateHelperItineraryRequest *fieldValue = [[CreateHelperItineraryRequest alloc] init];
          [fieldValue read: inProtocol];
          [self setRequest: fieldValue];
          [fieldValue release_stub];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"createItinerary_args"];
  if (__request_isset) {
    if (__request != nil) {
      [outProtocol writeFieldBeginWithName: @"request" type: TType_STRUCT fieldID: 1];
      [__request write: outProtocol];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"createItinerary_args("];
  [ms appendString: @"request:"];
  [ms appendFormat: @"%@", __request];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@interface CreateItinerary_result : NSObject <TBase, NSCoding> {
  CreateHelperItineraryResponse * __success;

  BOOL __success_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=success, setter=setSuccess:) CreateHelperItineraryResponse * success;
#endif

- (id) init;
- (id) initWithSuccess: (CreateHelperItineraryResponse *) success;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (CreateHelperItineraryResponse *) success;
- (void) setSuccess: (CreateHelperItineraryResponse *) success;
#endif
- (BOOL) successIsSet;

@end

@implementation CreateItinerary_result

- (id) init
{
  self = [super init];
#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
#endif
  return self;
}

- (id) initWithSuccess: (CreateHelperItineraryResponse *) success
{
  self = [super init];
  __success = [success retain_stub];
  __success_isset = YES;
  return self;
}

- (id) initWithCoder: (NSCoder *) decoder
{
  self = [super init];
  if ([decoder containsValueForKey: @"success"])
  {
    __success = [[decoder decodeObjectForKey: @"success"] retain_stub];
    __success_isset = YES;
  }
  return self;
}

- (void) encodeWithCoder: (NSCoder *) encoder
{
  if (__success_isset)
  {
    [encoder encodeObject: __success forKey: @"success"];
  }
}

- (void) dealloc
{
  [__success release_stub];
  [super dealloc_stub];
}

- (CreateHelperItineraryResponse *) success {
  return [[__success retain_stub] autorelease_stub];
}

- (void) setSuccess: (CreateHelperItineraryResponse *) success {
  [success retain_stub];
  [__success release_stub];
  __success = success;
  __success_isset = YES;
}

- (BOOL) successIsSet {
  return __success_isset;
}

- (void) unsetSuccess {
  [__success release_stub];
  __success = nil;
  __success_isset = NO;
}

- (void) read: (id <TProtocol>) inProtocol
{
  NSString * fieldName;
  int fieldType;
  int fieldID;

  [inProtocol readStructBeginReturningName: NULL];
  while (true)
  {
    [inProtocol readFieldBeginReturningName: &fieldName type: &fieldType fieldID: &fieldID];
    if (fieldType == TType_STOP) { 
      break;
    }
    switch (fieldID)
    {
      case 0:
        if (fieldType == TType_STRUCT) {
          CreateHelperItineraryResponse *fieldValue = [[CreateHelperItineraryResponse alloc] init];
          [fieldValue read: inProtocol];
          [self setSuccess: fieldValue];
          [fieldValue release_stub];
        } else { 
          [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        }
        break;
      default:
        [TProtocolUtil skipType: fieldType onProtocol: inProtocol];
        break;
    }
    [inProtocol readFieldEnd];
  }
  [inProtocol readStructEnd];
}

- (void) write: (id <TProtocol>) outProtocol {
  [outProtocol writeStructBeginWithName: @"CreateItinerary_result"];

  if (__success_isset) {
    if (__success != nil) {
      [outProtocol writeFieldBeginWithName: @"success" type: TType_STRUCT fieldID: 0];
      [__success write: outProtocol];
      [outProtocol writeFieldEnd];
    }
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
}

- (void) validate {
  // check for required fields
}

- (NSString *) description {
  NSMutableString * ms = [NSMutableString stringWithString: @"CreateItinerary_result("];
  [ms appendString: @"success:"];
  [ms appendFormat: @"%@", __success];
  [ms appendString: @")"];
  return [NSString stringWithString: ms];
}

@end

@implementation ItineraryThriftServiceClient
- (id) initWithProtocol: (id <TProtocol>) protocol
{
  return [self initWithInProtocol: protocol outProtocol: protocol];
}

- (id) initWithInProtocol: (id <TProtocol>) anInProtocol outProtocol: (id <TProtocol>) anOutProtocol
{
  self = [super init];
  inProtocol = [anInProtocol retain_stub];
  outProtocol = [anOutProtocol retain_stub];
  return self;
}

- (void) dealloc
{
  [inProtocol release_stub];
  [outProtocol release_stub];
  [super dealloc_stub];
}

- (void) send_createItinerary: (CreateHelperItineraryRequest *) request
{
  [outProtocol writeMessageBeginWithName: @"createItinerary" type: TMessageType_CALL sequenceID: 0];
  [outProtocol writeStructBeginWithName: @"createItinerary_args"];
  if (request != nil)  {
    [outProtocol writeFieldBeginWithName: @"request" type: TType_STRUCT fieldID: 1];
    [request write: outProtocol];
    [outProtocol writeFieldEnd];
  }
  [outProtocol writeFieldStop];
  [outProtocol writeStructEnd];
  [outProtocol writeMessageEnd];
  [[outProtocol transport] flush];
}

- (CreateHelperItineraryResponse *) recv_createItinerary
{
  int msgType = 0;
  [inProtocol readMessageBeginReturningName: nil type: &msgType sequenceID: NULL];
  if (msgType == TMessageType_EXCEPTION) {
    TApplicationException * x = [TApplicationException read: inProtocol];
    [inProtocol readMessageEnd];
    @throw x;
  }
  CreateItinerary_result * result = [[[CreateItinerary_result alloc] init] autorelease_stub];
  [result read: inProtocol];
  [inProtocol readMessageEnd];
  if ([result successIsSet]) {
    return [result success];
  }
  @throw [TApplicationException exceptionWithType: TApplicationException_MISSING_RESULT
                                           reason: @"createItinerary failed: unknown result"];
}

- (CreateHelperItineraryResponse *) createItinerary: (CreateHelperItineraryRequest *) request
{
  [self send_createItinerary : request];
  return [self recv_createItinerary];
}

@end

@implementation ItineraryThriftServiceProcessor

- (id) initWithItineraryThriftService: (id <ItineraryThriftService>) service
{
  self = [super init];
  if (!self) {
    return nil;
  }
  mService = [service retain_stub];
  mMethodMap = [[NSMutableDictionary dictionary] retain_stub];
  {
    SEL s = @selector(process_createItinerary_withSequenceID:inProtocol:outProtocol:);
    NSMethodSignature * sig = [self methodSignatureForSelector: s];
    NSInvocation * invocation = [NSInvocation invocationWithMethodSignature: sig];
    [invocation setSelector: s];
    [invocation retainArguments];
    [mMethodMap setValue: invocation forKey: @"createItinerary"];
  }
  return self;
}

- (id<ItineraryThriftService>) service
{
  return [[mService retain_stub] autorelease_stub];
}

- (BOOL) processOnInputProtocol: (id <TProtocol>) inProtocol
                 outputProtocol: (id <TProtocol>) outProtocol
{
  NSString * messageName;
  int messageType;
  int seqID;
  [inProtocol readMessageBeginReturningName: &messageName
                                       type: &messageType
                                 sequenceID: &seqID];
  NSInvocation * invocation = [mMethodMap valueForKey: messageName];
  if (invocation == nil) {
    [TProtocolUtil skipType: TType_STRUCT onProtocol: inProtocol];
    [inProtocol readMessageEnd];
    TApplicationException * x = [TApplicationException exceptionWithType: TApplicationException_UNKNOWN_METHOD reason: [NSString stringWithFormat: @"Invalid method name: '%@'", messageName]];
    [outProtocol writeMessageBeginWithName: messageName
                                      type: TMessageType_EXCEPTION
                                sequenceID: seqID];
    [x write: outProtocol];
    [outProtocol writeMessageEnd];
    [[outProtocol transport] flush];
    return YES;
  }
  // NSInvocation does not conform to NSCopying protocol
  NSInvocation * i = [NSInvocation invocationWithMethodSignature: [invocation methodSignature]];
  [i setSelector: [invocation selector]];
  [i setArgument: &seqID atIndex: 2];
  [i setArgument: &inProtocol atIndex: 3];
  [i setArgument: &outProtocol atIndex: 4];
  [i setTarget: self];
  [i invoke];
  return YES;
}

- (void) process_createItinerary_withSequenceID: (int32_t) seqID inProtocol: (id<TProtocol>) inProtocol outProtocol: (id<TProtocol>) outProtocol
{
  createItinerary_args * args = [[createItinerary_args alloc] init];
  [args read: inProtocol];
  [inProtocol readMessageEnd];
  CreateItinerary_result * result = [[CreateItinerary_result alloc] init];
  [result setSuccess: [mService createItinerary: [args request]]];
  [outProtocol writeMessageBeginWithName: @"createItinerary"
                                    type: TMessageType_REPLY
                              sequenceID: seqID];
  [result write: outProtocol];
  [outProtocol writeMessageEnd];
  [[outProtocol transport] flush];
  [result release_stub];
  [args release_stub];
}

- (void) dealloc
{
  [mService release_stub];
  [mMethodMap release_stub];
  [super dealloc_stub];
}

@end

