/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"

#import "authentication.h"

@interface LocationDto : NSObject <TBase, NSCoding> {
  int32_t __id;
  NSString * __code;
  NSString * __name;
  double __latitude;
  double __longitude;

  BOOL __id_isset;
  BOOL __code_isset;
  BOOL __name_isset;
  BOOL __latitude_isset;
  BOOL __longitude_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=id, setter=setId:) int32_t id;
@property (nonatomic, retain, getter=code, setter=setCode:) NSString * code;
@property (nonatomic, retain, getter=name, setter=setName:) NSString * name;
@property (nonatomic, getter=latitude, setter=setLatitude:) double latitude;
@property (nonatomic, getter=longitude, setter=setLongitude:) double longitude;
#endif

- (id) init;
- (id) initWithId: (int32_t) id code: (NSString *) code name: (NSString *) name latitude: (double) latitude longitude: (double) longitude;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) id;
- (void) setId: (int32_t) id;
#endif
- (BOOL) idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) code;
- (void) setCode: (NSString *) code;
#endif
- (BOOL) codeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) name;
- (void) setName: (NSString *) name;
#endif
- (BOOL) nameIsSet;

#if !__has_feature(objc_arc)
- (double) latitude;
- (void) setLatitude: (double) latitude;
#endif
- (BOOL) latitudeIsSet;

#if !__has_feature(objc_arc)
- (double) longitude;
- (void) setLongitude: (double) longitude;
#endif
- (BOOL) longitudeIsSet;

@end

@interface CityDto : NSObject <TBase, NSCoding> {
  int32_t __id;
  NSString * __code;
  NSString * __name;
  double __latitude;
  double __longitude;

  BOOL __id_isset;
  BOOL __code_isset;
  BOOL __name_isset;
  BOOL __latitude_isset;
  BOOL __longitude_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=id, setter=setId:) int32_t id;
@property (nonatomic, retain, getter=code, setter=setCode:) NSString * code;
@property (nonatomic, retain, getter=name, setter=setName:) NSString * name;
@property (nonatomic, getter=latitude, setter=setLatitude:) double latitude;
@property (nonatomic, getter=longitude, setter=setLongitude:) double longitude;
#endif

- (id) init;
- (id) initWithId: (int32_t) id code: (NSString *) code name: (NSString *) name latitude: (double) latitude longitude: (double) longitude;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) id;
- (void) setId: (int32_t) id;
#endif
- (BOOL) idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) code;
- (void) setCode: (NSString *) code;
#endif
- (BOOL) codeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) name;
- (void) setName: (NSString *) name;
#endif
- (BOOL) nameIsSet;

#if !__has_feature(objc_arc)
- (double) latitude;
- (void) setLatitude: (double) latitude;
#endif
- (BOOL) latitudeIsSet;

#if !__has_feature(objc_arc)
- (double) longitude;
- (void) setLongitude: (double) longitude;
#endif
- (BOOL) longitudeIsSet;

@end

@interface RegionDto : NSObject <TBase, NSCoding> {
  int32_t __id;
  NSString * __code;
  NSString * __name;
  double __latitude;
  double __longitude;

  BOOL __id_isset;
  BOOL __code_isset;
  BOOL __name_isset;
  BOOL __latitude_isset;
  BOOL __longitude_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=id, setter=setId:) int32_t id;
@property (nonatomic, retain, getter=code, setter=setCode:) NSString * code;
@property (nonatomic, retain, getter=name, setter=setName:) NSString * name;
@property (nonatomic, getter=latitude, setter=setLatitude:) double latitude;
@property (nonatomic, getter=longitude, setter=setLongitude:) double longitude;
#endif

- (id) init;
- (id) initWithId: (int32_t) id code: (NSString *) code name: (NSString *) name latitude: (double) latitude longitude: (double) longitude;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) id;
- (void) setId: (int32_t) id;
#endif
- (BOOL) idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) code;
- (void) setCode: (NSString *) code;
#endif
- (BOOL) codeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) name;
- (void) setName: (NSString *) name;
#endif
- (BOOL) nameIsSet;

#if !__has_feature(objc_arc)
- (double) latitude;
- (void) setLatitude: (double) latitude;
#endif
- (BOOL) latitudeIsSet;

#if !__has_feature(objc_arc)
- (double) longitude;
- (void) setLongitude: (double) longitude;
#endif
- (BOOL) longitudeIsSet;

@end

@interface CountryDto : NSObject <TBase, NSCoding> {
  int32_t __id;
  NSString * __code;
  NSString * __name;
  double __latitude;
  double __longitude;

  BOOL __id_isset;
  BOOL __code_isset;
  BOOL __name_isset;
  BOOL __latitude_isset;
  BOOL __longitude_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=id, setter=setId:) int32_t id;
@property (nonatomic, retain, getter=code, setter=setCode:) NSString * code;
@property (nonatomic, retain, getter=name, setter=setName:) NSString * name;
@property (nonatomic, getter=latitude, setter=setLatitude:) double latitude;
@property (nonatomic, getter=longitude, setter=setLongitude:) double longitude;
#endif

- (id) init;
- (id) initWithId: (int32_t) id code: (NSString *) code name: (NSString *) name latitude: (double) latitude longitude: (double) longitude;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) id;
- (void) setId: (int32_t) id;
#endif
- (BOOL) idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) code;
- (void) setCode: (NSString *) code;
#endif
- (BOOL) codeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) name;
- (void) setName: (NSString *) name;
#endif
- (BOOL) nameIsSet;

#if !__has_feature(objc_arc)
- (double) latitude;
- (void) setLatitude: (double) latitude;
#endif
- (BOOL) latitudeIsSet;

#if !__has_feature(objc_arc)
- (double) longitude;
- (void) setLongitude: (double) longitude;
#endif
- (BOOL) longitudeIsSet;

@end

@interface GetCountriesResponse : NSObject <TBase, NSCoding> {
  int32_t __errorCode;
  NSMutableArray * __countries;

  BOOL __errorCode_isset;
  BOOL __countries_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=errorCode, setter=setErrorCode:) int32_t errorCode;
@property (nonatomic, retain, getter=countries, setter=setCountries:) NSMutableArray * countries;
#endif

- (id) init;
- (id) initWithErrorCode: (int32_t) errorCode countries: (NSMutableArray *) countries;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) errorCode;
- (void) setErrorCode: (int32_t) errorCode;
#endif
- (BOOL) errorCodeIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) countries;
- (void) setCountries: (NSMutableArray *) countries;
#endif
- (BOOL) countriesIsSet;

@end

@interface GetRegionsResponse : NSObject <TBase, NSCoding> {
  int32_t __errorCode;
  NSMutableArray * __regions;

  BOOL __errorCode_isset;
  BOOL __regions_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=errorCode, setter=setErrorCode:) int32_t errorCode;
@property (nonatomic, retain, getter=regions, setter=setRegions:) NSMutableArray * regions;
#endif

- (id) init;
- (id) initWithErrorCode: (int32_t) errorCode regions: (NSMutableArray *) regions;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) errorCode;
- (void) setErrorCode: (int32_t) errorCode;
#endif
- (BOOL) errorCodeIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) regions;
- (void) setRegions: (NSMutableArray *) regions;
#endif
- (BOOL) regionsIsSet;

@end

@interface GetCitiesResponse : NSObject <TBase, NSCoding> {
  int32_t __errorCode;
  NSMutableArray * __cities;

  BOOL __errorCode_isset;
  BOOL __cities_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=errorCode, setter=setErrorCode:) int32_t errorCode;
@property (nonatomic, retain, getter=cities, setter=setCities:) NSMutableArray * cities;
#endif

- (id) init;
- (id) initWithErrorCode: (int32_t) errorCode cities: (NSMutableArray *) cities;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) errorCode;
- (void) setErrorCode: (int32_t) errorCode;
#endif
- (BOOL) errorCodeIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) cities;
- (void) setCities: (NSMutableArray *) cities;
#endif
- (BOOL) citiesIsSet;

@end

@interface GetRegionsAndCitiesByCountryRequest : NSObject <TBase, NSCoding> {
  int32_t __countryId;

  BOOL __countryId_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=countryId, setter=setCountryId:) int32_t countryId;
#endif

- (id) init;
- (id) initWithCountryId: (int32_t) countryId;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) countryId;
- (void) setCountryId: (int32_t) countryId;
#endif
- (BOOL) countryIdIsSet;

@end

@interface GetRegionsAndCitiesByCountryResponse : NSObject <TBase, NSCoding> {
  int32_t __errorCode;
  NSMutableArray * __regions;
  NSMutableArray * __cities;

  BOOL __errorCode_isset;
  BOOL __regions_isset;
  BOOL __cities_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=errorCode, setter=setErrorCode:) int32_t errorCode;
@property (nonatomic, retain, getter=regions, setter=setRegions:) NSMutableArray * regions;
@property (nonatomic, retain, getter=cities, setter=setCities:) NSMutableArray * cities;
#endif

- (id) init;
- (id) initWithErrorCode: (int32_t) errorCode regions: (NSMutableArray *) regions cities: (NSMutableArray *) cities;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) errorCode;
- (void) setErrorCode: (int32_t) errorCode;
#endif
- (BOOL) errorCodeIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) regions;
- (void) setRegions: (NSMutableArray *) regions;
#endif
- (BOOL) regionsIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) cities;
- (void) setCities: (NSMutableArray *) cities;
#endif
- (BOOL) citiesIsSet;

@end

@interface GetCitiesByRegionRequest : NSObject <TBase, NSCoding> {
  int32_t __regionId;

  BOOL __regionId_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=regionId, setter=setRegionId:) int32_t regionId;
#endif

- (id) init;
- (id) initWithRegionId: (int32_t) regionId;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) regionId;
- (void) setRegionId: (int32_t) regionId;
#endif
- (BOOL) regionIdIsSet;

@end

@interface GetCitiesByRegionResponse : NSObject <TBase, NSCoding> {
  int32_t __errorCode;
  NSMutableArray * __cities;

  BOOL __errorCode_isset;
  BOOL __cities_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=errorCode, setter=setErrorCode:) int32_t errorCode;
@property (nonatomic, retain, getter=cities, setter=setCities:) NSMutableArray * cities;
#endif

- (id) init;
- (id) initWithErrorCode: (int32_t) errorCode cities: (NSMutableArray *) cities;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) errorCode;
- (void) setErrorCode: (int32_t) errorCode;
#endif
- (BOOL) errorCodeIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) cities;
- (void) setCities: (NSMutableArray *) cities;
#endif
- (BOOL) citiesIsSet;

@end

@protocol RefDataThriftService <NSObject>
- (GetCountriesResponse *) getCountries: (SessionCredentials *) credentials;  // throws TException
- (GetRegionsResponse *) getRegions: (SessionCredentials *) credentials;  // throws TException
- (GetCitiesResponse *) getCities: (SessionCredentials *) credentials;  // throws TException
- (GetRegionsAndCitiesByCountryResponse *) getRegionsAndCitiesByCountry: (GetRegionsAndCitiesByCountryRequest *) request credentials: (SessionCredentials *) credentials;  // throws TException
- (GetCitiesByRegionResponse *) getCitiesByRegion: (GetCitiesByRegionRequest *) request credentials: (SessionCredentials *) credentials;  // throws TException
@end

@interface RefDataThriftServiceClient : NSObject <RefDataThriftService> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface RefDataThriftServiceProcessor : NSObject <TProcessor> {
  id <RefDataThriftService> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithRefDataThriftService: (id <RefDataThriftService>) service;
- (id<RefDataThriftService>) service;
@end

@interface refdataConstants : NSObject {
}
@end
