/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"

#import "authentication.h"

@interface CitySearchResultDto : NSObject <TBase, NSCoding> {
  int32_t __id;
  NSString * __displayName;

  BOOL __id_isset;
  BOOL __displayName_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=id, setter=setId:) int32_t id;
@property (nonatomic, retain, getter=displayName, setter=setDisplayName:) NSString * displayName;
#endif

- (id) init;
- (id) initWithId: (int32_t) id displayName: (NSString *) displayName;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) id;
- (void) setId: (int32_t) id;
#endif
- (BOOL) idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) displayName;
- (void) setDisplayName: (NSString *) displayName;
#endif
- (BOOL) displayNameIsSet;

@end

@interface SearchCitiesRequest : NSObject <TBase, NSCoding> {
  NSString * __searchText;
  int32_t __maxCount;

  BOOL __searchText_isset;
  BOOL __maxCount_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=searchText, setter=setSearchText:) NSString * searchText;
@property (nonatomic, getter=maxCount, setter=setMaxCount:) int32_t maxCount;
#endif

- (id) init;
- (id) initWithSearchText: (NSString *) searchText maxCount: (int32_t) maxCount;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) searchText;
- (void) setSearchText: (NSString *) searchText;
#endif
- (BOOL) searchTextIsSet;

#if !__has_feature(objc_arc)
- (int32_t) maxCount;
- (void) setMaxCount: (int32_t) maxCount;
#endif
- (BOOL) maxCountIsSet;

@end

@interface SearchCitiesResponse : NSObject <TBase, NSCoding> {
  int32_t __errorCode;
  NSMutableArray * __cities;

  BOOL __errorCode_isset;
  BOOL __cities_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=errorCode, setter=setErrorCode:) int32_t errorCode;
@property (nonatomic, retain, getter=cities, setter=setCities:) NSMutableArray * cities;
#endif

- (id) init;
- (id) initWithErrorCode: (int32_t) errorCode cities: (NSMutableArray *) cities;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) errorCode;
- (void) setErrorCode: (int32_t) errorCode;
#endif
- (BOOL) errorCodeIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) cities;
- (void) setCities: (NSMutableArray *) cities;
#endif
- (BOOL) citiesIsSet;

@end

@protocol RefDataThriftService <NSObject>
- (SearchCitiesResponse *) searchCities: (SearchCitiesRequest *) request credentials: (SessionCredentials *) credentials;  // throws TException
@end

@interface RefDataThriftServiceClient : NSObject <RefDataThriftService> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface RefDataThriftServiceProcessor : NSObject <TProcessor> {
  id <RefDataThriftService> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithRefDataThriftService: (id <RefDataThriftService>) service;
- (id<RefDataThriftService>) service;
@end

@interface refdataConstants : NSObject {
}
@end
