#!/bin/sh

if [ -z $AMITY_START_SCRIPT ]; then
	echo "AMITY_START_SCRIPT not specified. Existing..."
	exit 1
fi

cd `dirname $0`

SERVICE_NAME=$AMITY_START_SCRIPT
START_SCRIPT=./$AMITY_START_SCRIPT
TEMP_DIR=/var/tmp/jingyusoft
PID_PATH_NAME=$TEMP_DIR/${SERVICE_NAME}-pid
STDOUT_FILE_NAME=$TEMP_DIR/$SERVICE_NAME/stdout.log
STDERR_FILE_NAME=$TEMP_DIR/$SERVICE_NAME/stderr.log

echo "-------------------------------------"
echo "---   AMITY SERVICE INFORMATION   ---"
echo "-------------------------------------"
echo "Current Dir      = " `pwd`
echo "Service Name     = " $SERVICE_NAME
echo "Start Script     = " $START_SCRIPT
echo "Temp Dir         = " $TEMP_DIR
echo "PID_PATH_NAME    = " $PID_PATH_NAME
echo "STDOUT_FILE_NAME = " $STDOUT_FILE_NAME
echo "STDERR_FILE_NAME = " $STDERR_FILE_NAME
echo "-------------------------------------"

if [ ! -d $TEMP_DIR/$SERVICE_NAME ]; then
	mkdir -p $TEMP_DIR/$SERVICE_NAME
	echo "Temp directory created: " $TEMP_DIR/$SERVICE_NAME 
fi

case $1 in
    start)
        echo "Starting $SERVICE_NAME ..."
        if [ ! -f $PID_PATH_NAME ]; then
            $START_SCRIPT 2> $STDERR_FILE_NAME 1> $STDOUT_FILE_NAME &
                        echo $! > $PID_PATH_NAME
            echo "$SERVICE_NAME started ..."
        else
            echo "$SERVICE_NAME is already running ..."
        fi
    ;;
    stop)
        if [ -f $PID_PATH_NAME ]; then
            PID=$(cat $PID_PATH_NAME);
            echo "$SERVICE_NAME stoping ..."
            kill $PID;
            echo "$SERVICE_NAME stopped ..."
            rm $PID_PATH_NAME
        else
            echo "$SERVICE_NAME is not running ..."
        fi
    ;;
    restart)
        if [ -f $PID_PATH_NAME ]; then
            PID=$(cat $PID_PATH_NAME);
            echo "$SERVICE_NAME stopping ...";
            kill $PID;
            echo "$SERVICE_NAME stopped ...";
            rm $PID_PATH_NAME
            echo "$SERVICE_NAME starting ..."
			$START_SCRIPT 2> $STDERR_FILE_NAME 1> $STDOUT_FILE_NAME &
                        echo $! > $PID_PATH_NAME
            echo "$SERVICE_NAME started ..."
        else
            echo "$SERVICE_NAME is not running ..."
        fi
    ;;
esac 