package com.jingyusoft.amity.data.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ForeignKey;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Version;

import org.hibernate.envers.Audited;

import com.jingyusoft.amity.data.auditing.AuditableEntity;

@Entity
@Table(name = "facebook_user")
@Audited(withModifiedFlag = true)
public class FacebookUserEntity extends AuditableEntity {

	/**
	 * The Facebook ID of the user, not generated by Amity
	 */
	@Id
	@Column(name = "facebook_id")
	private long facebookId;

	@OneToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "amity_user_id", foreignKey = @ForeignKey(name = "fk_facebook_user_amity_user_id"))
	@Audited(withModifiedFlag = true)
	private AmityUserEntity amityUser;

	@Version
	@Column(name = "version_lock")
	private Integer versionLock;

	public AmityUserEntity getAmityUser() {
		return amityUser;
	}

	public long getFacebookId() {
		return facebookId;
	}

	public Integer getVersionLock() {
		return versionLock;
	}

	public void setAmityUser(AmityUserEntity amityUser) {
		this.amityUser = amityUser;
	}

	public void setFacebookId(long facebookId) {
		this.facebookId = facebookId;
	}

	public void setVersionLock(Integer versionLock) {
		this.versionLock = versionLock;
	}
}
