package com.jingyusoft.amity.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import org.hibernate.annotations.ForeignKey;

@Entity
@Table(name = "facebook_user")
public class FacebookUserEntity {

	/**
	 * The Facebook ID of the user, not generated by Amity
	 */
	@Id
	@Column(name = "facebook_id")
	private long facebookId;

	@OneToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "amity_user_id")
	@ForeignKey(name = "fk_facebook_user_amity_user_id")
	private AmityUserEntity amityUser;

	public AmityUserEntity getAmityUser() {
		return amityUser;
	}

	public long getFacebookId() {
		return facebookId;
	}

	public void setAmityUser(AmityUserEntity amityUser) {
		this.amityUser = amityUser;
	}

	public void setFacebookId(long facebookId) {
		this.facebookId = facebookId;
	}
}
